name = "NestedUnitRanges"
uuid = "032820ab-dc03-4b49-91f4-7d58d4da98b3"
authors = ["Kristof Cools <krcools@gmail.com> and contributors"]
version = "0.1-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"

[compat]
julia = "1.6"
AbstractTrees = "0.4.4"
BlockArrays = "0.16.24"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
